import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Button from '@/components/Button'
import ButtonGroup from '@/components/ButtonGroup'
import SignInButton from '@/components/SignInButton'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ButtonGroup>
          <SignInButton>Sign In</SignInButton>
          <Button>Sign Out</Button>
        </ButtonGroup>
        {children}
      </body>
    </html>
  )
}
